/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok.tugasgui;

/**
 *
 * @author Verel
 */

class bangun {
public float Lpersegi(float a,float b){
return (a*b);
}
public float Kpersegi(float a, float b){
return (2*(a+b));
}

public float Lsegitiga(float a,float b){
    return (a*b/2);
}
public float Ksegitiga(float a,float b){
    return (a+(2*b));
}

public float Llingkaran(float a){
    return  (22/7)*a*a;
}
public float Klingkaran(float a){
    return (22/7)*2*a;
}
public float Ljajar(float a,float t){
    return (a*t);
}
public float Kjajar(float a,float siMir){
    return (2*(a+siMir));
}
public float Lpersegipanjang(float a,float b){
return (a*b);
}
public float Kpersegipanjang(float a, float b){
return (2*(a+b));
}

public float volBalok(float panjang, float lebar, float tinggi) {
     return (panjang*lebar*tinggi);
}

public float lpBalok(float panjang, float lebar,float tinggi) {
     return (2*((panjang*lebar)+(panjang*tinggi)+(lebar*tinggi)));
    }

public float volPrismaSegitiga(float alas, float tinggi,float sisi) {
       return (1/2*alas*tinggi);
    }

public float lpPrismaSegitiga(float alas, float sisi,float sisiMir, float tinggi) {
        return ((2*1/2*sisi*sisiMir)+((sisi+sisiMir+alas)*tinggi));
    }
public float volTabung(float jari, float tinggi) {
       return (22/7*jari*jari*tinggi);
    }

public float lpTabung(float jari,float tinggi) {
        return (2*22/7*jari*(jari+tinggi));
    }

}

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioPersegiPanjang = new javax.swing.JRadioButton();
        jRadioJajarGenjang = new javax.swing.JRadioButton();
        jButtonHitung2D = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextHasilLuas = new javax.swing.JTextField();
        jTextHasilKeliling = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextDiagonal = new javax.swing.JTextField();
        jTextSisi = new javax.swing.JTextField();
        jTextAlas = new javax.swing.JTextField();
        jTextSisiMiring = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextJariJari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRadioPrismaSegitiga = new javax.swing.JRadioButton();
        jRadioTabung = new javax.swing.JRadioButton();
        jRadioKerucut = new javax.swing.JRadioButton();
        jRadioBola = new javax.swing.JRadioButton();
        jRadioLimasSegitiga = new javax.swing.JRadioButton();
        jRadioLimasSegiEmpat = new javax.swing.JRadioButton();
        jButtonHitung3D = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextHasilLuasPermukaan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextHasilVolume = new javax.swing.JTextField();
        jRadioBalok = new javax.swing.JRadioButton();
        jTextPanjang = new javax.swing.JTextField();
        jTextLebar = new javax.swing.JTextField();
        jTextTinggi = new javax.swing.JTextField();
        jRadioButtonPersegi = new javax.swing.JRadioButton();
        jRadioSegitigaSiku = new javax.swing.JRadioButton();
        jRadioLingkaran = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Perhitungan Bangun Ruang");

        jLabel2.setText("Panjang");

        jRadioPersegiPanjang.setText("Persegi Panjang");
        jRadioPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPersegiPanjangActionPerformed(evt);
            }
        });

        jRadioJajarGenjang.setText("Jajar Genjang");
        jRadioJajarGenjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioJajarGenjangActionPerformed(evt);
            }
        });

        jButtonHitung2D.setBackground(new java.awt.Color(204, 204, 204));
        jButtonHitung2D.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonHitung2D.setText("Hitung 2D");
        jButtonHitung2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitung2DActionPerformed(evt);
            }
        });

        jLabel12.setText("Luas");

        jLabel13.setText("Keliling");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioJajarGenjang)
                    .addComponent(jRadioPersegiPanjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHitung2D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioJajarGenjang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioPersegiPanjang)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jButtonHitung2D))
        );

        jLabel3.setText("Lebar");

        jLabel4.setText("Tinggi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Bangun 2D");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Bangun 3D");

        jTextDiagonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiagonalActionPerformed(evt);
            }
        });

        jTextSisiMiring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSisiMiringActionPerformed(evt);
            }
        });

        jLabel7.setText("Sisi Miring");

        jLabel8.setText("Diagonal");

        jLabel9.setText("Sisi");

        jLabel10.setText("Jari-Jari");

        jTextJariJari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextJariJariActionPerformed(evt);
            }
        });

        jLabel11.setText("Alas");

        jRadioPrismaSegitiga.setText("Prisma Segitiga");
        jRadioPrismaSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPrismaSegitigaActionPerformed(evt);
            }
        });

        jRadioTabung.setText("Tabung");
        jRadioTabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioTabungActionPerformed(evt);
            }
        });

        jRadioKerucut.setText("Kerucut");
        jRadioKerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioKerucutActionPerformed(evt);
            }
        });

        jRadioBola.setText("Bola");
        jRadioBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBolaActionPerformed(evt);
            }
        });

        jRadioLimasSegitiga.setText("Limas Segitiga");
        jRadioLimasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLimasSegitigaActionPerformed(evt);
            }
        });

        jRadioLimasSegiEmpat.setText("Limas Segi Empat");
        jRadioLimasSegiEmpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLimasSegiEmpatActionPerformed(evt);
            }
        });

        jButtonHitung3D.setBackground(new java.awt.Color(204, 204, 204));
        jButtonHitung3D.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonHitung3D.setText("Hitung 3D");
        jButtonHitung3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitung3DActionPerformed(evt);
            }
        });

        jLabel14.setText("Volume");

        jLabel15.setText("Luas Permukaan");

        jRadioBalok.setText("Balok");
        jRadioBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBalokActionPerformed(evt);
            }
        });

        jTextPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPanjangActionPerformed(evt);
            }
        });

        jTextTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTinggiActionPerformed(evt);
            }
        });

        jRadioButtonPersegi.setText("Persegi");
        jRadioButtonPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPersegiActionPerformed(evt);
            }
        });

        jRadioSegitigaSiku.setText("Segitiga Siku-siku");
        jRadioSegitigaSiku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSegitigaSikuActionPerformed(evt);
            }
        });

        jRadioLingkaran.setText("Lingkaran");
        jRadioLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLingkaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextDiagonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jTextSisi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextAlas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextTinggi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextLebar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextPanjang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextJariJari, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextSisiMiring))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jRadioLingkaran))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jRadioSegitigaSiku))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextHasilKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextHasilLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(230, 230, 230))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonHitung3D, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextHasilLuasPermukaan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextHasilVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioPrismaSegitiga)
                                    .addComponent(jRadioTabung)
                                    .addComponent(jRadioKerucut)
                                    .addComponent(jRadioBalok))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioLimasSegitiga)
                                    .addComponent(jRadioLimasSegiEmpat)
                                    .addComponent(jRadioBola))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButtonPersegi))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioSegitigaSiku)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRadioLingkaran)
                            .addGap(7, 7, 7))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextHasilLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextHasilKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextSisiMiring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioPrismaSegitiga)
                            .addComponent(jRadioLimasSegiEmpat)
                            .addComponent(jTextDiagonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioTabung)
                            .addComponent(jRadioLimasSegitiga)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextSisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextAlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextJariJari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioKerucut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioBalok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonHitung3D)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioBola))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextHasilVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextHasilLuasPermukaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPersegiActionPerformed
        // TODO add your handling code here:
         if (jRadioButtonPersegi.isSelected()==true) {
            jRadioSegitigaSiku.setSelected(false);
            jRadioJajarGenjang.setSelected(false);
            jRadioLingkaran.setSelected(false);
            jRadioPersegiPanjang.setSelected(false);
            jRadioPrismaSegitiga.setSelected(false);
            jRadioBalok.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);

            jTextLebar.setEditable(true);
            jTextPanjang.setEditable(true);

            jTextAlas.setEditable(false);
            jTextSisiMiring.setEditable(false);
            jTextJariJari.setEditable(false);
            jTextTinggi.setEditable(false);
            jTextDiagonal.setEditable(false);
            jTextSisi.setEditable(false);

            jTextJariJari.setText("0");
            jTextAlas.setText("0");
            jTextSisiMiring.setText("0");
            jTextTinggi.setText("0");
            jTextPanjang.setText("");
            jTextLebar.setText("");
            jTextDiagonal.setText("0");
            jTextSisi.setText("0");
            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");

        }
    }//GEN-LAST:event_jRadioButtonPersegiActionPerformed

    private void jRadioTabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioTabungActionPerformed
        // TODO add your handling code here:
        if (jRadioTabung.isSelected()==true)
        {
            jRadioPrismaSegitiga.setSelected(false);
            jRadioBalok.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);

            jTextLebar.setEditable(false);
            jTextPanjang.setEditable(false);
            jTextSisiMiring.setEditable(false);
            jTextTinggi.setEditable(true);
            jTextDiagonal.setEditable(false);
            jTextSisi.setEditable(false);
            jTextAlas.setEditable(false);
            jTextJariJari.setEditable(true);

            jTextLebar.setText("0");
            jTextPanjang.setText("0");
            jTextSisiMiring.setText("0");
            jTextTinggi.setText("");
            jTextDiagonal.setText("0");
            jTextSisi.setText("0");
            jTextAlas.setText("0");
            jTextJariJari.setText("");

            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");
        }
    }//GEN-LAST:event_jRadioTabungActionPerformed

    private void jRadioLimasSegiEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLimasSegiEmpatActionPerformed
        // TODO add your handling code here:
        if (jRadioLimasSegiEmpat.isSelected()==true) 
        {
            jRadioPrismaSegitiga.setSelected(false);
            jRadioBalok.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);
            
            
            jTextLebar.setEditable(false);
            jTextPanjang.setEditable(false);
            jTextSisiMiring.setEditable(false);
            jTextTinggi.setEditable(true);
            jTextDiagonal.setEditable(false);
            jTextSisi.setEditable(true);
            jTextAlas.setEditable(false);
            jTextJariJari.setEditable(false);
            
            jTextLebar.setText("0"); 
            jTextPanjang.setText("0");
            jTextSisiMiring.setText("0");
            jTextTinggi.setText("");
            jTextDiagonal.setText("0");
            jTextSisi.setText("");            
            jTextAlas.setText("0");
            jTextJariJari.setText("0");
                       
            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");
        }
    }//GEN-LAST:event_jRadioLimasSegiEmpatActionPerformed

    private void jButtonHitung3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitung3DActionPerformed
        // TODO add your handling code here:
        float panjang,lebar,alas,tinggi,jari,sisiMir,sisi,diagonal,lp,vol;
        panjang = Float.valueOf(jTextPanjang.getText());
        lebar = Float.valueOf(jTextLebar.getText());
        alas = Float.valueOf(jTextAlas.getText());
        tinggi = Float.valueOf(jTextTinggi.getText());
        jari = Float.valueOf(jTextJariJari.getText());
        sisiMir = Float.valueOf(jTextSisiMiring.getText());
        sisi = Float.valueOf(jTextSisi.getText());
        diagonal = Float.valueOf(jTextDiagonal.getText());
        
       
        bangun Bangun = new bangun ();
        if (jRadioPrismaSegitiga.isSelected()==true) {
            jTextHasilVolume.setText(String.valueOf(Bangun.volPrismaSegitiga(alas,sisi, tinggi)));
            jTextHasilLuasPermukaan.setText(String.valueOf(Bangun.lpPrismaSegitiga(alas,sisi,sisiMir, tinggi)));
        }
        else if  (jRadioBalok.isSelected()==true) {
            jTextHasilVolume.setText(String.valueOf(Bangun.volBalok(panjang, lebar, tinggi)));
            jTextHasilLuasPermukaan.setText(String.valueOf(Bangun.lpBalok(panjang, lebar,tinggi)));
        }
        else if  (jRadioTabung.isSelected()==true) {
            jTextHasilVolume.setText(String.valueOf(Bangun.volTabung(jari,tinggi)));
            jTextHasilLuasPermukaan.setText(String.valueOf(Bangun.lpTabung(jari,tinggi)));
        }
    }//GEN-LAST:event_jButtonHitung3DActionPerformed

    private void jRadioSegitigaSikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSegitigaSikuActionPerformed
        // TODO add your handling code here:
        if (jRadioSegitigaSiku.isSelected()==true) {
            jRadioButtonPersegi.setSelected(false);
            jRadioLingkaran.setSelected(false);
            jRadioJajarGenjang.setSelected(false);
            jRadioPersegiPanjang.setSelected(false);
            jRadioPrismaSegitiga.setSelected(false);
            jRadioBalok.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);

            jTextAlas.setEditable(true);
            jTextSisiMiring.setEditable(true);
            jTextTinggi.setEditable(true);

            jTextPanjang.setEditable(false);
            jTextLebar.setEditable(false);
            jTextJariJari.setEditable(false);
            jTextDiagonal.setEditable(false);
            jTextSisi.setEditable(false);

            jTextTinggi.setText("");
            jTextLebar.setText("0");
            jTextPanjang.setText("0");
            jTextSisiMiring.setText("");
            jTextAlas.setText("");
            jTextJariJari.setText("0");
            jTextDiagonal.setText("0");
            jTextSisi.setText("0");
            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");

        }
    }//GEN-LAST:event_jRadioSegitigaSikuActionPerformed

    private void jButtonHitung2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitung2DActionPerformed
        // TODO add your handling code here:
        float panjang,lebar,alas,tinggi,jari,sisiMir,sisi,diagonal,luas,keliling;
        panjang = Float.valueOf(jTextPanjang.getText());
        lebar = Float.valueOf(jTextLebar.getText());
        alas = Float.valueOf(jTextAlas.getText());
        tinggi = Float.valueOf(jTextTinggi.getText());
        jari = Float.valueOf(jTextJariJari.getText());
        sisiMir = Float.valueOf(jTextSisiMiring.getText());
        sisi = Float.valueOf(jTextSisi.getText());
        diagonal = Float.valueOf(jTextDiagonal.getText());
        
        
        
        bangun Bangun = new bangun();
        
        
            jTextHasilLuas.setText(String.valueOf(Bangun.Lpersegi(panjang, lebar)));
            jTextHasilKeliling.setText(String.valueOf(Bangun.Kpersegi(panjang, lebar)));
        
            jTextHasilLuas.setText(String.valueOf(Bangun.Lsegitiga(alas, tinggi)));
            jTextHasilKeliling.setText(String.valueOf(Bangun.Ksegitiga(alas, sisiMir)));
        
            jTextHasilLuas.setText(String.valueOf(Bangun.Llingkaran(jari)));
            jTextHasilKeliling.setText(String.valueOf(Bangun.Klingkaran(jari)));
        
            jTextHasilLuas.setText(String.valueOf(Bangun.Lpersegi(tinggi, alas)));
            jTextHasilKeliling.setText(String.valueOf(Bangun.Kpersegi(alas, sisiMir)));
        
        
            jTextHasilLuas.setText(String.valueOf(Bangun.Lpersegi(panjang, lebar)));
            jTextHasilKeliling.setText(String.valueOf(Bangun.Kpersegi(panjang, lebar)));
    }//GEN-LAST:event_jButtonHitung2DActionPerformed

    private void jRadioKerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioKerucutActionPerformed
        // TODO add your handling code here:
        if (jRadioKerucut.isSelected()==true) 
        {
            jRadioPrismaSegitiga.setSelected(false);
            jRadioBalok.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);
            
            
            jTextLebar.setEditable(false);
            jTextPanjang.setEditable(false);
            jTextSisiMiring.setEditable(true);
            jTextTinggi.setEditable(true);
            jTextDiagonal.setEditable(false);
            jTextSisi.setEditable(false);
            jTextAlas.setEditable(false);
            jTextJariJari.setEditable(true);
            
            jTextLebar.setText("0"); 
            jTextPanjang.setText("0");
            jTextJariJari.setText("");
            jTextTinggi.setText("");
            jTextDiagonal.setText("0");
            jTextSisi.setText("0");            
            jTextAlas.setText("0");
            jTextJariJari.setText("");
                       
            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");
        }
    }//GEN-LAST:event_jRadioKerucutActionPerformed

    private void jRadioLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLingkaranActionPerformed
        // TODO add your handling code here:
        if (jRadioLingkaran.isSelected()==true)
        {
            jRadioButtonPersegi.setSelected(false);
            jRadioSegitigaSiku.setSelected(false);
            jRadioJajarGenjang.setSelected(false);
            jRadioPersegiPanjang.setSelected(false);
            jRadioPrismaSegitiga.setSelected(false);
            jRadioBalok.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);

            jTextSisiMiring.setEditable(false);
            jTextAlas.setEditable(false);
            jTextJariJari.setEditable(true);

            jTextPanjang.setEditable(false);
            jTextLebar.setEditable(false);
            jTextTinggi.setEditable(true);

            jTextTinggi.setText("0");
            jTextPanjang.setText("0");
            jTextSisiMiring.setText("0");
            jTextAlas.setText("0");
            jTextJariJari.setText("");
            jTextLebar.setText("0");
            jTextDiagonal.setText("0");
            jTextSisi.setText("0");
            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");
        }
    }//GEN-LAST:event_jRadioLingkaranActionPerformed

    private void jRadioJajarGenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioJajarGenjangActionPerformed
        // TODO add your handling code here:
        if (jRadioJajarGenjang.isSelected()==true)
        {
            jRadioSegitigaSiku.setSelected(false);
            jRadioLingkaran.setSelected(false);
            jRadioButtonPersegi.setSelected(false);
            jRadioPersegiPanjang.setSelected(false);
            jRadioPrismaSegitiga.setSelected(false);
            jRadioBalok.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);

            jTextSisiMiring.setEditable(true);
            jTextAlas.setEditable(true);
            jTextTinggi.setEditable(true);

            jTextPanjang.setEditable(false);
            jTextLebar.setEditable(false);
            jTextJariJari.setEditable(false);

            jTextTinggi.setText("");
            jTextPanjang.setText("0");
            jTextSisiMiring.setText("");
            jTextAlas.setText("");
            jTextJariJari.setText("0");
            jTextLebar.setText("0");
            jTextDiagonal.setText("0");
            jTextSisi.setText("0");
            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");
        }
    }//GEN-LAST:event_jRadioJajarGenjangActionPerformed

    private void jRadioPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPersegiPanjangActionPerformed
        // TODO add your handling code here:
        if (jRadioPersegiPanjang.isSelected()==true)
        {
            jRadioButtonPersegi.setSelected(false);
            jRadioSegitigaSiku.setSelected(false);
            jRadioLingkaran.setSelected(false);
            jRadioJajarGenjang.setSelected(false);
            jRadioPrismaSegitiga.setSelected(false);
            jRadioBalok.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);

            jTextLebar.setEditable(true);
            jTextPanjang.setEditable(true);

            jTextAlas.setEditable(false);
            jTextSisiMiring.setEditable(false);
            jTextJariJari.setEditable(false);
            jTextTinggi.setEditable(false);
            jTextDiagonal.setEditable(false);
            jTextSisi.setEditable(false);

            jTextJariJari.setText("0");
            jTextAlas.setText("0");
            jTextSisiMiring.setText("0");
            jTextTinggi.setText("0");
            jTextPanjang.setText("");
            jTextLebar.setText("");
            jTextDiagonal.setText("0");
            jTextSisi.setText("0");
            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");
        }
    }//GEN-LAST:event_jRadioPersegiPanjangActionPerformed

    private void jRadioPrismaSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPrismaSegitigaActionPerformed
        // TODO add your handling code here:
        if (jRadioPrismaSegitiga.isSelected()==true)
        {
            jRadioBalok.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);

            jTextLebar.setEditable(false);
            jTextPanjang.setEditable(false);
            jTextSisiMiring.setEditable(true);
            jTextTinggi.setEditable(true);
            jTextDiagonal.setEditable(false);
            jTextSisi.setEditable(true);
            jTextAlas.setEditable(true);
            jTextJariJari.setEditable(false);

            jTextLebar.setText("0");
            jTextPanjang.setText("0");
            jTextSisiMiring.setText("");
            jTextTinggi.setText("");
            jTextDiagonal.setText("0");
            jTextSisi.setText("");
            jTextAlas.setText("");
            jTextJariJari.setText("0");

            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");
        }
    }//GEN-LAST:event_jRadioPrismaSegitigaActionPerformed

    private void jRadioBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBolaActionPerformed
        // TODO add your handling code here:
        if (jRadioBola.isSelected()==true) 
        {
            jRadioPrismaSegitiga.setSelected(false);
            jRadioBalok.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);
            
            
            jTextLebar.setEditable(false);
            jTextPanjang.setEditable(false);
            jTextSisiMiring.setEditable(false);
            jTextTinggi.setEditable(false);
            jTextDiagonal.setEditable(false);
            jTextSisi.setEditable(false);
            jTextAlas.setEditable(false);
            jTextJariJari.setEditable(true);
            
            jTextLebar.setText("0"); 
            jTextPanjang.setText("0");
            jTextSisiMiring.setText("0");
            jTextTinggi.setText("0");
            jTextDiagonal.setText("0");
            jTextSisi.setText("0");            
            jTextAlas.setText("0");
            jTextJariJari.setText("");
                       
            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");
    }
    }//GEN-LAST:event_jRadioBolaActionPerformed

    private void jRadioLimasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLimasSegitigaActionPerformed
        // TODO add your handling code here:
        if (jRadioLimasSegitiga.isSelected()==true) 
        {
            jRadioPrismaSegitiga.setSelected(false);
            jRadioBalok.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            
            
            jTextLebar.setEditable(false);
            jTextPanjang.setEditable(false);
            jTextSisiMiring.setEditable(false);
            jTextTinggi.setEditable(true);
            jTextDiagonal.setEditable(false);
            jTextSisi.setEditable(true);
            jTextAlas.setEditable(true);
            jTextJariJari.setEditable(false);
            
            jTextLebar.setText("0"); 
            jTextPanjang.setText("0");
            jTextSisiMiring.setText("0");
            jTextTinggi.setText("");
            jTextDiagonal.setText("0");
            jTextSisi.setText("");            
            jTextAlas.setText("");
            jTextJariJari.setText("0");
                       
            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");
        }
    }//GEN-LAST:event_jRadioLimasSegitigaActionPerformed

    private void jTextPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPanjangActionPerformed

    private void jTextJariJariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextJariJariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextJariJariActionPerformed

    private void jTextSisiMiringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSisiMiringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSisiMiringActionPerformed

    private void jRadioBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBalokActionPerformed
        // TODO add your handling code here:
        if (jRadioBalok.isSelected()==true)
        {
            jRadioPrismaSegitiga.setSelected(false);
            jRadioTabung.setSelected(false);
            jRadioKerucut.setSelected(false);
            jRadioBola.setSelected(false);
            jRadioLimasSegiEmpat.setSelected(false);
            jRadioLimasSegitiga.setSelected(false);

            jTextLebar.setEditable(true);
            jTextPanjang.setEditable(true);
            jTextSisiMiring.setEditable(false);
            jTextTinggi.setEditable(true);
            jTextDiagonal.setEditable(false);
            jTextSisi.setEditable(false);
            jTextAlas.setEditable(false);
            jTextJariJari.setEditable(false);

            jTextLebar.setText("");
            jTextPanjang.setText("");
            jTextSisiMiring.setText("0");
            jTextTinggi.setText("");
            jTextDiagonal.setText("0");
            jTextSisi.setText("0");
            jTextAlas.setText("0");
            jTextJariJari.setText("0");

            jTextHasilLuas.setText("");
            jTextHasilKeliling.setText("");
            jTextHasilVolume.setText("");
            jTextHasilLuasPermukaan.setText("");
        }
    }//GEN-LAST:event_jRadioBalokActionPerformed

    private void jTextTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTinggiActionPerformed

    private void jTextDiagonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiagonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiagonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHitung2D;
    private javax.swing.JButton jButtonHitung3D;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioBalok;
    private javax.swing.JRadioButton jRadioBola;
    private javax.swing.JRadioButton jRadioButtonPersegi;
    private javax.swing.JRadioButton jRadioJajarGenjang;
    private javax.swing.JRadioButton jRadioKerucut;
    private javax.swing.JRadioButton jRadioLimasSegiEmpat;
    private javax.swing.JRadioButton jRadioLimasSegitiga;
    private javax.swing.JRadioButton jRadioLingkaran;
    private javax.swing.JRadioButton jRadioPersegiPanjang;
    private javax.swing.JRadioButton jRadioPrismaSegitiga;
    private javax.swing.JRadioButton jRadioSegitigaSiku;
    private javax.swing.JRadioButton jRadioTabung;
    private javax.swing.JTextField jTextAlas;
    private javax.swing.JTextField jTextDiagonal;
    private javax.swing.JTextField jTextHasilKeliling;
    private javax.swing.JTextField jTextHasilLuas;
    private javax.swing.JTextField jTextHasilLuasPermukaan;
    private javax.swing.JTextField jTextHasilVolume;
    private javax.swing.JTextField jTextJariJari;
    private javax.swing.JTextField jTextLebar;
    private javax.swing.JTextField jTextPanjang;
    private javax.swing.JTextField jTextSisi;
    private javax.swing.JTextField jTextSisiMiring;
    private javax.swing.JTextField jTextTinggi;
    // End of variables declaration//GEN-END:variables
}
